### ISSUE TITLE
Make absolute path "/images/[..]" relative "images/[..]"?

### ISSUE THREAD

**Issue by hartwork** [jshou/xiangqi_viewer#13]
Hi Josh,

I noticed when cloning and running this locally, none of the images show because of the leading slash in the image URLs. What do you think about dropping that leading slash to make it work unpatched locally?

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by hartwork** [comment]
@jshou any thoughts?

**Comment by hartwork** [comment]
@jshou does dropping the slashes have any downsides? I believe it would make things work for all cases. Should I prepare a pull request?

**Comment by jshou** [comment]
sure go for it!

**Comment by hartwork** [comment]
@jshou here you go: #14

**Comment by jshou** [comment]
Merged! Thank you for the PR. :)
